### ISSUE TITLE
Nexus Link changed

### ISSUE THREAD

**Issue by DeltaGW2** [Sognus/Gw2-Bosses#7]
If you are using Nexus link the name for it now always is "DL_NEXUS_LINK" without the process ID. The process ID is appended internally.
As per api-cdi docs
![image](https://github.com/Sognus/Gw2-Bosses/assets/46466697/ad987a2e-d1df-4bc4-be17-1094a287b79a)

**Comment by Sognus** [comment]
Fixed in 0.9.1.0
